### ISSUE TITLE
Hashtag

### ISSUE THREAD

**Issue by 2ec0b4** [p0nce/bitoduc.fr#14]
Pourquoi avoir modifié la traduction du mot "Hashtag" ? Il est officiellement traduit par "mot-dièse" : http://legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000026972451 ou "mot-clic" http://fr.wikipedia.org/wiki/Hashtag

**Comment by p0nce** [comment]
Bonjour,

Tout d'abord, `bitoduc.fr` n'a aucun objectif particulier de correction ou de vérité. Son unique but est de réchauffer le débat et provoquer des festivals de post enflammés.

Vous conviendrez, @2ec0b4,  après avoir lu https://github.com/p0nce/bitoduc.fr/pull/13 que «mot-dièse» n'est ni plus, ni moins correct que «croisiquette», bien au contraire.

Si vous êtes inquiets quand à la validité du lexique présenté, je vous enjoint à lire le code source qui sépare strictement ces deux catégories.

**Comment by 2ec0b4** [comment]
Merci @p0nce pour ces précisions. J'avais en effet noté les différences de catégorie de certains mots mais avais manqué la référence à #13 .

Enfin, voyez cela comme une goutte d'huile venant alimenter le feu des commentaires : notez quand même que bitoduc.fr se positionne comme "la référence sur les termes informatiques en français" (cf. le titre de la page).
