### ISSUE TITLE
Le site n'est pas très accueillant depuis un ordiphone

### ISSUE THREAD

**Issue by emillon** [p0nce/bitoduc.fr#15]
La règle CSS `largeur: 800px` sur `#tout` (habilement nommé!) oblige le site à défiler horizontalement sur un ordiphone. Le simple remplacement par `largeur-max: 800px` semble suffisant pour améliorer l'expérience.

Bien sûr, tant qu'il n'existe pas un système pour écrire des règles CSS dans notre langue, il faudra se contenter de `max-width: 800px;`.

**Comment by p0nce** [comment]
En effet, mon expérience des sites "mobiles en premier" est limitée. Dans un monde de plus en plus dangereux, et qui attaque les fondements même de notre culture, il me semble important de pouvoir accéder à bitoduc dans n'importe quel situation.

**Comment by 2ec0b4** [comment]
Attention à l'utilisation du terme "ordiphone" qui peut porter à confusion (est-ce un ordinateur équipé d'un téléphone ?). Il serait préférable d'utiliser le terme "malinphone" #Mes2centimes

**Comment by p0nce** [comment]
C'est maintenant réparé sur la branche maître avec https://github.com/p0nce/bitoduc.fr/commit/70cf265c38bcd78b8eaa4e4a23e84b4e714db5e7
Merci pour le rapport de bogue !
