### ISSUE TITLE
Un équivalent pour «commit»

### ISSUE THREAD

**Issue by p0nce** [p0nce/bitoduc.fr#16]

**Comment by emillon** [comment]
[Le livre officiel](http://git-scm.com/book/fr/) utilise *commit*. C'est dommage. Pour "un commit" il y a éventuellement "changement". Pour "to commit", on peut utiliser "enregistrer" mais il y a une perte sémantique.

**Comment by p0nce** [comment]
Changement ne me semble pas assez précis.

Propositions: 
- un validat (lien avec base de données conservé)
- un quanta de code
- un progrès
- un codon / un codat
- un changeat?

**Comment by p0nce** [comment]
- un atome de code
- un codatomique (vs datatomique pour un commit BDD)
- un codon

**Comment by emillon** [comment]
J'ajoute un *codunit* (cf [répunit](https://fr.wikipedia.org/wiki/R%C3%A9punit)). À noter que *un quanta* n'est pas correct, il s'agit d'un *quantum* pour rester fidèle au latin.

Pourquoi ne pas emprunter au vocabulaire de la géographie? Un commit peut alors être une borne, un délimiteur, un piquet sémantique; chargé de communiquer aux développeurs l'information "vous êtes ici".

Dans un contexte git, on peut aussi évoquer un *haché* (de version?). (notons qu'alors "commit-ish" se traduit alors par "hach-iche" ou plutôt hachoïde).

Notez également que j'*adore* l'italique.

**Comment by p0nce** [comment]
Un « piquet » pourrait bien être un "tag" au sens de git.

J'aime bien « quantum », non seulement celui-ci est indivisible par étymologie, mais celà peut immédiatement évoquer "Code quantum", cette célèbre [série](http://img238.imageshack.us/img238/1074/al8sk.jpg) faisant hommage aux probabilités.

Et pourquoi pas un « trait » ? 
Avec un trait on fabrique des lignes (des branches?), un trait amène d'un point à un autre. Il est le constituant d'un tout plus grand que lui ; on peut _tirer un trait_ ou _prendre un trait_, que ce soit avec des _petits traits_ ou à _grand traits_. 
Dans une réunion debout francophile, on pourra entendre :
« J'ai tiré un gros trait, j'ai vu que vous aviez bien poussé vers le prochain jalon. »

Enfin le champ lexical du dessin vient à notre secours : on comprendra bien qu'un « trait » peut-être « hachuré », disposant d'un résumé numérique.

Mais un commit est-il un point dans l'espace ou un lien entre deux points ? Même si seconde proposition est attrayante, il semble que ce soit la première qui prime dans les gestionnaires de versions en usage.

**Comment by p0nce** [comment]
Je suis parti sur « atome de code » du coup.
