### ISSUE TITLE
Ajouter les mots de la liste suivante

### ISSUE THREAD

**Issue by p0nce** [p0nce/bitoduc.fr#22]
Un généreux donateur m'a envoyé une liste admirablement documentée de mots ne figurant pas dans notre liste. Renommez le document suivant en .doc pour la consulter.

![terme anglais doc](https://cloud.githubusercontent.com/assets/1067485/7925082/526bcc38-08c1-11e5-9b26-b26f66836628.png)

**Comment by ProgVal** [comment]
.png pour un document Word ?

**Comment by p0nce** [comment]
> Renommez le document suivant en .doc pour la consulter.

C'est un palliatif pour pouvoir placer le document dans ce ticket.

**Comment by p0nce** [comment]
C'est fait.
