### ISSUE TITLE
Que s’est-il passé ?

### ISSUE THREAD

**Issue by ProgVal** [p0nce/bitoduc.fr#24]
Le site est vide / non servi, et la branche maitresse a reçu [ceci](https://github.com/p0nce/bitoduc.fr/commit/d640adb0324a092321a646865bcdfc4f25e3ea8e).

**Comment by p0nce** [comment]
J'ai essayé d'héberger le site sur Github directement pour éviter les déploiements manuels.

Tout est maintenant ici :
https://github.com/p0nce/bitoduc.fr/tree/gh-pages

Chez moi (département de l'Isère) ça marche, alors je ne sais pas trop d'où ça vient.

**Comment by emillon** [comment]
Pour ce type d'hébergement, il faut habituellement un nom DNS en CNAME et non en A.

Notez que cela est normalement impossible pour des sites à la racine de la zone DNS (`bitoduc.fr`), mais possible pour des sous-domaines (`www.bitoduc.fr`).

**Comment by ProgVal** [comment]
Je ne vois pas de CNAME associé à bitoduc.fr.

**Comment by p0nce** [comment]
Avez-vous rafraîchi votre tampon DNS ?

**Comment by emillon** [comment]
Oh, [Github semble supporter cette configuration pour des champs A également](https://help.github.com/articles/tips-for-configuring-an-a-record-with-your-dns-provider/). Nous vivons une époque intéressante.

**Comment by ProgVal** [comment]
On 26/10/2015 14:43, Guillaume Piolat wrote:
> Avez-vous rafraîchi votre tampon DNS ?

Faire une requête directement au serveur maitre ne change rien.

```
 progval@ion  ~/src  dig @dns105.ovh.net bitoduc.fr CNAME

; <<>> DiG 9.9.5-9+deb8u3-Debian <<>> @dns105.ovh.net bitoduc.fr CNAME
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 42005
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;bitoduc.fr.			IN	CNAME

;; AUTHORITY SECTION:
bitoduc.fr.		300	IN	SOA	dns105.ovh.net. tech.ovh.net. 2015102501 86400
3600 3600000 300

;; Query time: 54 msec
;; SERVER: 213.251.188.149#53(213.251.188.149)
;; WHEN: Mon Oct 26 14:46:29 CET 2015
;; MSG SIZE  rcvd: 94
```

**Comment by p0nce** [comment]
Fin de l'alerte, c'est maintenant rustiné.
